#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        #        show_sql: true
#        format_sql: true
#
#logging:
#  level:
#    org.hibernate.SQL: debug
#
#spring:
#  datasource:
#    url : jdbc:mysql://finwave-db.cvb3rorgyw8t.ap-northeast-2.rds.amazonaws.com:3306/finwaveDB?serverTimezone=UTC
#    username: master
#    password: finwave2023
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        #        show_sql: true
#        format_sql: true
#        default_batch_fetch_size: 1000 #최적화 옵션
#
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.springframework.web.socket: DEBUG

spring:
  datasource:
    url: jdbc:mysql://finwave-db.cvb3rorgyw8t.ap-northeast-2.rds.amazonaws.com:3306/finwaveDB?serverTimezone=UTC
    username: master
    password: finwave2023
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web.socket: DEBUG